# Generated by Django 6.0.2 on 2026-03-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Ethereum-compatible wallet address (0x…)', max_length=42, unique=True)),
                ('provider', models.CharField(choices=[('trust_wallet', 'Trust Wallet'), ('metamask', 'MetaMask'), ('walletconnect', 'WalletConnect'), ('other', 'Other')], default='trust_wallet', max_length=20)),
                ('nonce', models.CharField(default='', help_text='One-time nonce the user must sign to authenticate.', max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chain_id', models.IntegerField(default=1, help_text='EVM chain id (1=Ethereum, 56=BSC, 137=Polygon …)')),
            ],
            options={
                'verbose_name': 'Wallet Session',
                'verbose_name_plural': 'Wallet Sessions',
                'ordering': ['-last_seen'],
            },
        ),
    ]
