"""
Django settings for TradingWeb project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load .env file (must be at project root)
load_dotenv(Path(__file__).resolve().parent.parent / ".env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pp34lhmse6*aq&nv27k3m-_zgup*a81xuj-+^xj08iszkf%()3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'corsheaders',
    'django_celery_results',
    'trading',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TradingWeb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'trading' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TradingWeb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# ------------------------------------------------------------------ #
#  Database — PostgreSQL (production) / SQLite (fallback)
# ------------------------------------------------------------------ #
_DB_ENGINE = os.environ.get('DB_ENGINE', 'sqlite3')

if _DB_ENGINE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'tradingweb'),
            'USER': os.environ.get('DB_USER', 'tradingweb'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'trading' / 'static']

# ------------------------------------------------------------------ #
#  Django Channels / ASGI
# ------------------------------------------------------------------ #
ASGI_APPLICATION = 'TradingWeb.asgi.application'

# Use Redis if available, fall back to InMemory
_REDIS_URL = os.environ.get('REDIS_URL', '')

if _REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [_REDIS_URL],
                'capacity': 1500,
                'expiry': 60,
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# ------------------------------------------------------------------ #
#  Celery — Task queue (Redis broker)
# ------------------------------------------------------------------ #
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', _REDIS_URL or 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = 'django-db'  # Store results in PostgreSQL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 300          # 5 min hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 240     # 4 min soft limit
CELERY_WORKER_PREFETCH_MULTIPLIER = 1 # One task at a time per worker
CELERY_TASK_ACKS_LATE = True          # Ack after task completes

# ── Celery Beat schedule (periodic tasks) ──
from celery.schedules import crontab  # noqa: E402
CELERY_BEAT_SCHEDULE = {
    'backtest-daily-summary': {
        'task': 'trading.tasks.daily_backtest_summary',
        'schedule': crontab(hour=0, minute=30),
    },
    'optimize-strategy-daily': {
        'task': 'trading.tasks.run_strategy_optimization',
        'schedule': crontab(hour=1, minute=0),
    },
    'cleanup-old-snapshots': {
        'task': 'trading.tasks.cleanup_old_data',
        'schedule': crontab(hour=3, minute=0),
    },
}

# ------------------------------------------------------------------ #
#  Caches — Redis (production) / LocMem (fallback)
# ------------------------------------------------------------------ #
if _REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _REDIS_URL,
            'OPTIONS': {
                'db': 1,
            },
        },
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        },
    }

# ------------------------------------------------------------------ #
#  CORS – allow frontend dev servers
# ------------------------------------------------------------------ #
CORS_ALLOW_ALL_ORIGINS = DEBUG  # In production, set CORS_ALLOWED_ORIGINS instead
CORS_ALLOW_CREDENTIALS = True

# ------------------------------------------------------------------ #
#  Logging
# ------------------------------------------------------------------ #
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'trading': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
